app:
  name: spring-boot-example
  description: ${app.name} is a Spring Boot application

logging:
  level:
    root: DEBUG
    org:
      springframework:
        web: ERROR

my:
  secret: ${random.value}
  number: ${random.int}
#    less:
#      than:
#        ten: ${random.int(10)}
#    in:
#      range: ${random.int[1024,65536]}
#  bignumber: ${random.long}
#  uuid: ${random.uuid}

server:
  port: 8080
  tomcat:
    max-threads: 20

# 配置数据源
#spring:
#  datasource:
#    url: jdbc:mysql://localhost/readinglist
#    username: root
#    password: 111111

amazon:
  associateId: habuma-20

spring:
  profiles:
    active: production